openapi: 3.0.3
info:
  title: Kanban Board API
  description: API documentation for the Organization-level Kanban app with user, organization, and tracker management.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    OrganizationDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        isCreatedBy:
          type: boolean

    CreateOrganizationRequest:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string

    UserLoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    TokenResponse:
      type: object
      properties:
        token:
          type: string

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: JWT Token returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

  /organizations:
    get:
      summary: Get all organizations for the logged-in user
      responses:
        '200':
          description: List of organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationDTO'
      security:
        - bearerAuth: []

    post:
      summary: Create a new organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrganizationRequest'
      responses:
        '201':
          description: Organization created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDTO'
      security:
        - bearerAuth: []

  /organizations/{orgId}/add-user/{userId}:
    post:
      summary: Add a user to an organization
      parameters:
        - name: orgId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User added
        '400':
          description: Invalid operation
      security:
        - bearerAuth: []
